#!/usr/bin/env bash
# lib/config.sh — Chinna persistent config system (Godspeed style)
# Files:
#   ~/.chinna/env     → API keys + runtime settings (chmod 600)
#   ~/.chinna/models  → Active AI model presets

CHINNA_ENV_FILE="${CHINNA_HOME}/env"
CHINNA_MODELS_FILE="${CHINNA_HOME}/models"

# ────────────────────────────────────────────────────────────────
# Core: Safe key=value management (like setenv in Godspeed)
# ────────────────────────────────────────────────────────────────
chinna_setenv() {
    local file="$1" key="$2" value="$3"

    [ -z "$file" ] && { fail "chinna_setenv: file required"; return 1; }
    [ -z "$key" ] && { fail "chinna_setenv: key required"; return 1; }

    mkdir -p "$(dirname "$file")"

    # Remove existing key (if any)
    if [ -f "$file" ]; then
        grep -v "^${key}=" "$file" > "${file}.tmp" 2>/dev/null || true
        mv "${file}.tmp" "$file"
    fi

    # Append new value (quote if it contains spaces or special chars)
    if [[ "$value" =~ [[:space:]] || "$value" =~ [\"\'] ]]; then
        printf '%s="%s"\n' "$key" "$value" >> "$file"
    else
        printf '%s=%s\n' "$key" "$value" >> "$file"
    fi

    chmod 600 "$file" 2>/dev/null || true
}

# Load both env and models into current shell
chinna_load_env() {
    if [ -f "$CHINNA_ENV_FILE" ]; then
        # shellcheck disable=SC1090
        source "$CHINNA_ENV_FILE"
    fi
    if [ -f "$CHINNA_MODELS_FILE" ]; then
        # shellcheck disable=SC1090
        source "$CHINNA_MODELS_FILE"
    fi
}

# Create default files if missing
chinna_write_defaults() {
    mkdir -p "$CHINNA_HOME"

    if [ ! -f "$CHINNA_ENV_FILE" ]; then
        cat > "$CHINNA_ENV_FILE" <<'EOF'
# Chinna Environment — API keys and settings (chmod 600)
# Generated by chinna config

# === AI Providers ===
# OPENROUTER_API_KEY=
# ANTHROPIC_API_KEY=
# OPENAI_API_KEY=

# === Feature Flags ===
APPAUTOMATIONMODE=off
APPNOTIFYSOUND="/System/Library/Sounds/Glass.aiff"
APPNOTIFYSPEAK=off

# === Paths ===
CHINNA_HOME="$HOME/.chinna"
EOF
        chmod 600 "$CHINNA_ENV_FILE"
        info "Created $CHINNA_ENV_FILE"
    fi

    if [ ! -f "$CHINNA_MODELS_FILE" ]; then
        cat > "$CHINNA_MODELS_FILE" <<'EOF'
# Chinna AI Model Presets
# Switch with: chinna model-set <preset>

ACTIVE_MODEL="openai/gpt-4o-mini"

# Presets (used by chinna ai / free / pro)
MODEL_coder="openai/gpt-4o"
MODEL_reasoning="anthropic/claude-3.5-sonnet"
MODEL_small="openai/gpt-4o-mini"
MODEL_gemma="google/gemma-2-9b-it:free"
MODEL_llama70="meta-llama/llama-3.3-70b-instruct:free"
MODEL_free="meta-llama/llama-3.3-70b-instruct:free"
MODEL_sonnet4="anthropic/claude-3.5-sonnet"
MODEL_opus4="anthropic/claude-3-opus"
MODEL_haiku4="anthropic/claude-3-haiku"
EOF
        chmod 600 "$CHINNA_MODELS_FILE"
        info "Created $CHINNA_MODELS_FILE"
    fi
}

# ────────────────────────────────────────────────────────────────
# Model Management (Godspeed style)
# ────────────────────────────────────────────────────────────────
chinna_model_set() {
    local preset="${1:-}"

    if [ -z "$preset" ]; then
        echo "Available presets:"
        grep '^MODEL_' "$CHINNA_MODELS_FILE" 2>/dev/null | sed 's/MODEL_//' | sed 's/=/ → /' || echo "  (no models file)"
        echo ""
        echo "Current active: ${ACTIVE_MODEL:-<none>}"
        return 0
    fi

    # Load current models
    chinna_load_env

    local varname="MODEL_${preset}"
    local new_model="${!varname:-}"

    if [ -z "$new_model" ]; then
        fail "Unknown model preset: $preset"
        echo "Try: chinna model-set coder | reasoning | sonnet4 | free | small"
        return 1
    fi

    chinna_setenv "$CHINNA_MODELS_FILE" "ACTIVE_MODEL" "$new_model"
    export ACTIVE_MODEL="$new_model"

    ok "Active model set to: $new_model (preset: $preset)"
}

# ────────────────────────────────────────────────────────────────
# Provider Setup (secure, no echo)
# ────────────────────────────────────────────────────────────────
chinna_setup_openrouter() {
    echo -n "Paste your OpenRouter API key (sk-or-...): "
    read -rs key
    echo ""

    if [ -z "$key" ]; then
        fail "No key provided"
        return 1
    fi

    chinna_setenv "$CHINNA_ENV_FILE" "OPENROUTER_API_KEY" "$key"
    ok "OpenRouter key saved securely to $CHINNA_ENV_FILE"
}

chinna_setup_anthropic() {
    echo -n "Paste your Anthropic API key (sk-ant-...): "
    read -rs key
    echo ""

    if [ -z "$key" ]; then
        fail "No key provided"
        return 1
    fi

    chinna_setenv "$CHINNA_ENV_FILE" "ANTHROPIC_API_KEY" "$key"
    ok "Anthropic key saved securely"
}

# ────────────────────────────────────────────────────────────────
# Convenience
# ────────────────────────────────────────────────────────────────
chinna_config_status() {
    section "Chinna Config"

    echo "  Env file:     $CHINNA_ENV_FILE"
    [ -f "$CHINNA_ENV_FILE" ] && ok "exists (chmod $(stat -f %A "$CHINNA_ENV_FILE" 2>/dev/null || stat -c %a "$CHINNA_ENV_FILE"))" || warn "missing"

    echo "  Models file:  $CHINNA_MODELS_FILE"
    [ -f "$CHINNA_MODELS_FILE" ] && ok "exists" || warn "missing"

    chinna_load_env

    echo ""
    echo "  OpenRouter:   ${OPENROUTER_API_KEY:+set (len=${#OPENROUTER_API_KEY})}"
    echo "  Anthropic:    ${ANTHROPIC_API_KEY:+set}"
    echo "  OpenAI:       ${OPENAI_API_KEY:+set}"
    echo ""
    echo "  Active Model: ${ACTIVE_MODEL:-<not set>}"
    echo "  Automation:   ${APPAUTOMATIONMODE:-off}"
}
# ── Prompt 9 + 15: WhatsApp CLI helper ──────────────────────
chinna_whatsapp() {
    local number="${1:-}"
    local message="${2:-}"

    if [ -z "$number" ]; then
        # Interactive mode
        echo -n "  Phone number (with country code, digits only): "
        read -r number
        echo -n "  Message: "
        read -r message
    fi

    # Normalize: strip all non-digits
    local clean
    clean=$(echo "$number" | tr -cd '[:digit:]')

    if [ -z "$clean" ]; then
        fail "Invalid phone number"
        return 1
    fi

    if [ -z "$message" ]; then
        local url="https://wa.me/${clean}"
    else
        local encoded
        encoded=$(python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1]))" "$message" 2>/dev/null || echo "$message")
        local url="https://wa.me/${clean}?text=${encoded}"
    fi

    open "$url" 2>/dev/null || open "https://web.whatsapp.com" 2>/dev/null
    ok "Opening WhatsApp link: $url"
    mac_notify "WhatsApp" "Opening chat with +${clean}"
}

chinna_open_whatsapp() {
    open -a WhatsApp 2>/dev/null || open "https://web.whatsapp.com" 2>/dev/null
    ok "WhatsApp opened"
}
