#!/usr/bin/env bash
# lib/stack.sh — Project stack detection + auto-install + sandbox preview

source "$CHINNA_LIB/notify.sh" 2>/dev/null

# ─── Colors (inherited from main) ─────────────────────────────
R='\033[0;31m'; G='\033[0;32m'; Y='\033[0;33m'; C='\033[0;36m'
ORANGE='\033[38;5;208m'; BOLD='\033[1m'; D='\033[2m'; RESET='\033[0m'

ok()   { echo -e "  ${G}✓${RESET} $1"; }
warn() { echo -e "  ${Y}!${RESET} $1"; }
fail() { echo -e "  ${R}✗${RESET} $1"; }
info() { echo -e "  ${C}ℹ${RESET} $1"; }

progress() {
    local msg="$1"
    local pct="${2:-50}"
    local filled=$(( pct * 30 / 100 ))
    local bar=""
    for ((i=0;i<filled;i++)); do bar+="█"; done
    for ((i=filled;i<30;i++)); do bar+="░"; done
    local color="$G"
    [ "$pct" -gt 70 ] && color="$Y"
    [ "$pct" -gt 85 ] && color="$R"
    printf "\r  ${color}%s${RESET} %3d%%  %s" "$bar" "$pct" "$msg"
}

# ─── Ensure tool is installed via brew ────────────────────────
ensure_tool() {
    local tool="$1"
    local brew_pkg="${2:-$tool}"
    if ! command -v "$tool" >/dev/null 2>&1; then
        warn "$tool not found — installing via brew..."
        brew install "$brew_pkg" >/dev/null 2>&1 && ok "$tool installed" || fail "Could not install $tool"
    else
        ok "$tool ready"
    fi
}

ensure_brew_service() {
    local svc="$1"
    if ! brew services list 2>/dev/null | grep -q "^$svc.*started"; then
        warn "Starting $svc..."
        brew services start "$svc" >/dev/null 2>&1 && ok "$svc started"
    else
        ok "$svc already running"
    fi
}

# ─── Generate mock .env from .env.example ─────────────────────
generate_env() {
    local dir="${1:-.}"
    local env_example=""
    for f in .env.example .env.sample .env.template env.example; do
        [ -f "$dir/$f" ] && env_example="$dir/$f" && break
    done

    if [ -f "$dir/.env" ]; then
        info ".env already exists — skipping"
        return 0
    fi

    if [ -n "$env_example" ]; then
        cp "$env_example" "$dir/.env"
        # Replace placeholder values with mock values
        sed -i '' \
            's|=your_.*|=mock_dev_key_chinna|g;
             s|=<.*>|=mock_dev_key_chinna|g;
             s|=REPLACE_ME|=mock_dev_key_chinna|g;
             s|=YOUR_.*|=mock_dev_key_chinna|g;
             s|=sk-.*|=sk-mock-chinna-dev-key-000000000000000|g;
             s|=http://localhost:\([0-9]*\)|=http://localhost:\1|g' \
            "$dir/.env" 2>/dev/null
        ok "Generated .env from $env_example (mock keys injected)"
    else
        # Create minimal .env
        cat > "$dir/.env" <<'ENV'
# Generated by Chinna — replace with real values for production
NODE_ENV=development
PORT=3000
DATABASE_URL=postgresql://localhost:5432/dev_db
API_KEY=mock_dev_key_chinna
SECRET_KEY=mock_secret_chinna_dev
NEXT_PUBLIC_API_URL=http://localhost:3000
ENV
        ok "Created minimal .env with mock keys"
    fi
}

# ─── Detect project stack ──────────────────────────────────────
detect_stack() {
    local dir="${1:-.}"

    # Next.js
    if [ -f "$dir/package.json" ] && grep -q '"next"' "$dir/package.json" 2>/dev/null; then
        echo "nextjs"; return 0
    fi
    # Expo / React Native
    if [ -f "$dir/package.json" ] && grep -q '"expo"' "$dir/package.json" 2>/dev/null; then
        echo "expo"; return 0
    fi
    # Vite / React
    if [ -f "$dir/package.json" ] && grep -q '"vite"' "$dir/package.json" 2>/dev/null; then
        echo "vite"; return 0
    fi
    # Plain Node
    if [ -f "$dir/package.json" ]; then
        echo "node"; return 0
    fi
    # Flutter
    if [ -f "$dir/pubspec.yaml" ]; then
        echo "flutter"; return 0
    fi
    # FastAPI / Python
    if [ -f "$dir/requirements.txt" ] && grep -qi "fastapi" "$dir/requirements.txt" 2>/dev/null; then
        echo "fastapi"; return 0
    fi
    # Django
    if [ -f "$dir/requirements.txt" ] && grep -qi "django" "$dir/requirements.txt" 2>/dev/null; then
        echo "django"; return 0
    fi
    # Generic Python
    if [ -f "$dir/requirements.txt" ] || [ -f "$dir/pyproject.toml" ] || [ -f "$dir/setup.py" ]; then
        echo "python"; return 0
    fi
    # Go
    if [ -f "$dir/go.mod" ]; then echo "go"; return 0; fi
    # Rust
    if [ -f "$dir/Cargo.toml" ]; then echo "rust"; return 0; fi
    # Ruby
    if [ -f "$dir/Gemfile" ]; then echo "ruby"; return 0; fi

    echo "unknown"
    return 1
}

# ─── Stack runners ─────────────────────────────────────────────
run_nextjs() {
    local dir="${1:-.}"
    echo -e "\n  ${ORANGE}▶ Next.js project detected${RESET}\n"
    ensure_tool node node
    ensure_tool npm node
    generate_env "$dir"

    info "Installing dependencies..."
    cd "$dir"
    progress "npm install" 20; npm install >/dev/null 2>&1
    progress "npm install done" 100; echo ""

    local port=3000
    info "Starting dev server on :$port"
    (sleep 2; open "http://localhost:$port") &
    (sleep 2; code "$dir" 2>/dev/null || true) &
    chinna_ok_toast "Next.js Running" "http://localhost:$port — VS Code opened"
    npm run dev
}

run_vite() {
    local dir="${1:-.}"
    echo -e "\n  ${ORANGE}▶ Vite/React project detected${RESET}\n"
    ensure_tool node node
    generate_env "$dir"
    cd "$dir"
    progress "npm install" 20; npm install >/dev/null 2>&1
    progress "done" 100; echo ""
    local port=5173
    (sleep 2; open "http://localhost:$port") &
    (sleep 2; code "$dir" 2>/dev/null || true) &
    chinna_ok_toast "Vite Running" "http://localhost:$port"
    npm run dev
}

run_expo() {
    local dir="${1:-.}"
    echo -e "\n  ${ORANGE}▶ Expo/React Native project detected${RESET}\n"
    ensure_tool node node
    ensure_tool npx node
    generate_env "$dir"
    cd "$dir"
    npm install >/dev/null 2>&1
    (sleep 3; code "$dir" 2>/dev/null || true) &
    chinna_ok_toast "Expo Starting" "Scan QR code in terminal"
    npx expo start
}

run_node() {
    local dir="${1:-.}"
    echo -e "\n  ${ORANGE}▶ Node.js project detected${RESET}\n"
    ensure_tool node node
    generate_env "$dir"
    cd "$dir"
    npm install >/dev/null 2>&1
    local start_cmd="start"
    grep -q '"dev"' package.json 2>/dev/null && start_cmd="dev"
    (sleep 2; code "$dir" 2>/dev/null || true) &
    chinna_ok_toast "Node.js Starting" "npm run $start_cmd"
    npm run "$start_cmd"
}

run_flutter() {
    local dir="${1:-.}"
    echo -e "\n  ${ORANGE}▶ Flutter project detected${RESET}\n"
    ensure_tool flutter flutter
    cd "$dir"
    info "Running flutter pub get..."
    flutter pub get 2>/dev/null
    (sleep 2; code "$dir" 2>/dev/null || true) &
    chinna_ok_toast "Flutter Starting" "flutter run"
    flutter run
}

run_fastapi() {
    local dir="${1:-.}"
    echo -e "\n  ${ORANGE}▶ FastAPI project detected${RESET}\n"
    ensure_tool python3 python@3.12
    generate_env "$dir"
    cd "$dir"
    python3 -m venv .venv >/dev/null 2>&1
    source .venv/bin/activate
    pip install -r requirements.txt -q
    local port=8000
    (sleep 2; open "http://localhost:$port/docs") &
    (sleep 2; code "$dir" 2>/dev/null || true) &
    chinna_ok_toast "FastAPI Running" "http://localhost:$port/docs"
    uvicorn main:app --reload --port "$port" 2>/dev/null || \
    python3 -m uvicorn main:app --reload --port "$port"
}

run_django() {
    local dir="${1:-.}"
    echo -e "\n  ${ORANGE}▶ Django project detected${RESET}\n"
    ensure_tool python3 python@3.12
    generate_env "$dir"
    cd "$dir"
    python3 -m venv .venv >/dev/null 2>&1
    source .venv/bin/activate
    pip install -r requirements.txt -q
    python3 manage.py migrate >/dev/null 2>&1
    local port=8000
    (sleep 2; open "http://localhost:$port") &
    chinna_ok_toast "Django Running" "http://localhost:$port"
    python3 manage.py runserver
}

run_python() {
    local dir="${1:-.}"
    echo -e "\n  ${ORANGE}▶ Python project detected${RESET}\n"
    ensure_tool python3 python@3.12
    generate_env "$dir"
    cd "$dir"
    python3 -m venv .venv >/dev/null 2>&1
    source .venv/bin/activate
    pip install -r requirements.txt -q 2>/dev/null || true
    (sleep 1; code "$dir" 2>/dev/null || true) &
    chinna_ok_toast "Python Ready" "venv activated, deps installed"
    local main_file=$(ls main.py app.py run.py server.py 2>/dev/null | head -1)
    if [ -n "$main_file" ]; then
        python3 "$main_file"
    else
        info "No main entry point found. Dropping into venv shell."
        $SHELL
    fi
}

run_go() {
    local dir="${1:-.}"
    echo -e "\n  ${ORANGE}▶ Go project detected${RESET}\n"
    ensure_tool go go
    cd "$dir"
    go mod tidy >/dev/null 2>&1
    chinna_ok_toast "Go Starting" "go run ."
    go run .
}

run_rust() {
    local dir="${1:-.}"
    echo -e "\n  ${ORANGE}▶ Rust project detected${RESET}\n"
    ensure_tool cargo rust
    cd "$dir"
    chinna_ok_toast "Rust Building" "cargo run"
    cargo run
}

# ─── Main stack runner ─────────────────────────────────────────
run_project() {
    local dir="${1:-$(pwd)}"
    local stack
    stack=$(detect_stack "$dir")

    echo ""
    echo -e "  ${BOLD}${ORANGE}🚀 CHINNA SANDBOX${RESET}"
    echo -e "  ${D}Detected stack: ${RESET}${BOLD}$stack${RESET}"
    echo ""

    case "$stack" in
        nextjs)  run_nextjs "$dir" ;;
        vite)    run_vite "$dir" ;;
        expo)    run_expo "$dir" ;;
        node)    run_node "$dir" ;;
        flutter) run_flutter "$dir" ;;
        fastapi) run_fastapi "$dir" ;;
        django)  run_django "$dir" ;;
        python)  run_python "$dir" ;;
        go)      run_go "$dir" ;;
        rust)    run_rust "$dir" ;;
        unknown)
            warn "Could not detect stack in: $dir"
            echo -ne "  ${Y}Tell me the stack (nextjs/vite/flutter/fastapi/node):${RESET} "
            read -r manual_stack
            run_project_by_name "$manual_stack" "$dir"
            ;;
    esac
}

run_project_by_name() {
    local name="$1"; local dir="${2:-.}"
    case "$name" in
        nextjs|next)  run_nextjs "$dir" ;;
        vite|react)   run_vite "$dir" ;;
        expo|rn)      run_expo "$dir" ;;
        flutter)      run_flutter "$dir" ;;
        fastapi|api)  run_fastapi "$dir" ;;
        django)       run_django "$dir" ;;
        python|py)    run_python "$dir" ;;
        go)           run_go "$dir" ;;
        rust)         run_rust "$dir" ;;
        node)         run_node "$dir" ;;
        *) fail "Unknown stack: $name" ;;
    esac
}

# ─── Smart deploy ──────────────────────────────────────────────
deploy_project() {
    local dir="${1:-.}"
    echo -e "\n  ${BOLD}${ORANGE}🚀 DEPLOY${RESET}\n"

    # Detect platform from project files
    if [ -f "$dir/vercel.json" ] || [ -f "$dir/.vercel/project.json" ]; then
        info "Vercel project detected"
        ensure_tool vercel vercel
        cd "$dir" && vercel --prod
        chinna_ok_toast "Deployed to Vercel" "Check vercel.app dashboard"
    elif [ -f "$dir/netlify.toml" ]; then
        info "Netlify project detected"
        ensure_tool netlify netlify-cli
        cd "$dir" && netlify deploy --prod
    elif [ -f "$dir/railway.json" ] || [ -f "$dir/.railway" ]; then
        info "Railway project detected"
        ensure_tool railway railway
        cd "$dir" && railway up
    else
        warn "No deployment config found (vercel.json / netlify.toml / railway.json)"
        echo -ne "  Deploy to (vercel/netlify/railway): "
        read -r platform
        case "$platform" in
            vercel)  ensure_tool vercel vercel; cd "$dir" && vercel --prod ;;
            netlify) ensure_tool netlify netlify-cli; cd "$dir" && netlify deploy --prod ;;
            railway) ensure_tool railway railway; cd "$dir" && railway up ;;
        esac
    fi
}

# ─── AI git commit ─────────────────────────────────────────────
git_ai_commit() {
    local api_key="${OPENROUTER_API_KEY:-}"
    local diff
    diff=$(git diff --cached 2>/dev/null || git diff 2>/dev/null | head -200)

    if [ -z "$diff" ]; then
        warn "Nothing staged. Running: git add -A"
        git add -A
        diff=$(git diff --cached | head -200)
    fi

    if [ -z "$api_key" ]; then
        echo -ne "  ${C}Commit message:${RESET} "
        read -r msg
        git commit -m "$msg"
        return
    fi

    info "Generating commit message with AI..."
    local msg
    msg=$(curl -s "https://openrouter.ai/api/v1/chat/completions" \
        -H "Authorization: Bearer $api_key" \
        -H "Content-Type: application/json" \
        -d "$(jq -n --arg diff "$diff" '{
            model: "meta-llama/llama-3.3-70b-instruct:free",
            max_tokens: 80,
            messages: [{
                role: "user",
                content: ("Write a concise git commit message (max 72 chars) for this diff. Reply with ONLY the message, no quotes, no explanation:\n\n" + $diff)
            }]
        }')" 2>/dev/null | jq -r '.choices[0].message.content // "chore: update"')

    msg=$(echo "$msg" | head -1 | cut -c1-72)
    echo -e "  ${G}Suggested:${RESET} $msg"
    echo -ne "  ${Y}Use this? [Y/n/edit]:${RESET} "
    read -r yn
    case "$yn" in
        n|N) echo -ne "  Commit message: "; read -r msg ;;
        e|E) echo -ne "  Edit: "; read -r msg ;;
    esac
    git commit -m "$msg"
    echo -ne "  ${Y}Push now? [Y/n]:${RESET} "
    read -r push_yn
    [[ ! "$push_yn" =~ ^[Nn]$ ]] && git push && chinna_ok_toast "Pushed" "$msg"
}
